### ISSUE TITLE
json data is escaped during rendering 

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#45]
[Raw json](https://github.com/Coachonko/coachonko.com/blob/2c4c8846ade497644a7f11e775c75f9fb425c7c4/server/handlers/dark/LinkedData.jsx) is automatically escaped during rendering. 
What is the recommended technique to insert json in a script tag? It is necessary for json+ld
I am looking for an equivalent to dangerouslySetInnerHTML, [something similar to this](https://github.com/Coachonko/coachonko.com/blob/master/server/handlers/dark/LinkedData.jsx)

**Comment by atellmer** [comment]
When developing Dark, I missed this point. It seemed unimportant to me. Now I think it might be worth adding support for `dangerouslySetInnerHTML`.
