### ISSUE TITLE
No render, no error problem

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#50]
I have run into the situation where I am getting no application rendering, at the same time I am also not getting any error message.
This has happened while attempting to use the `TranslationsProvider` component exported by [dark-translator](https://github.com/Coachonko/dark-translator), you can see the setup [here](https://github.com/Coachonko/coachonko.com/commit/81a483ccb8483cd65585fe89ae389a67a1b76062).

It appears that the `TranslationsProvider` component doesn't run at all, a simple `console.log()` at the top of the component doesn't output anything.
How would you debug this? Do you have a guess on what the problem may be?

**Comment by Coachonko** [comment]
Turns out it's a Bun issue again.

**Comment by atellmer** [comment]
Ok, nice new package =)

**Comment by Coachonko** [comment]
> Ok, nice new package =)

I am not sure I am utilizing the correct approach. I feel like atoms would work well for this but I am not too comfortable with Dark's API.

--- Bun rant below:

Bun seems to have issues resolving soft links. Linking the package to my current working project didn't work, soft linking the src directory also didn't work. Copying the src directory worked, but it's a pain in the ass to keep the 2 directories in sync.

Bun also doesn't seem to understand what peerDependencies are: it bundles all depending code anyway and the project that uses the package gets duplicated dependencies in the final bundle. 

The low-level Bun API work great and it is so fast, but the bundling and linking package situation is pretty bad. Since Dark doesn't require custom JSX transforms the transpiling is super fast on Bun though

**Comment by atellmer** [comment]
It seems to me that for things like i18n or theming it is more correct to use the context, because it is rarely switched. Atoms impose their own limitations because we have to deal not with values, but with objects with their own internal kitchen. And, to be honest, this is a rather experimental feature. You can offer your vision of the API as well.

New things always contain mistakes. I think Dark will not be an exception to this series, apparently this is the law of no matter how complex systems are.

**Comment by Coachonko** [comment]
> It seems to me that for things like i18n or theming it is more correct to use the context, because it is rarely switched. Atoms impose their own limitations because we have to deal not with values, but with objects with their own internal kitchen. And, to be honest, this is a rather experimental feature. You can offer your vision of the API as well.

I wrote the "core" of this i18n solution for Inferno, that I've used before but I think I like Dark more for the next projects I have in mind. In Inferno I used an event emitter to tell each component that required a rerender to rerender when the language changed.
Atoms are event emitters so I thought they would do that job instead.

The API used by Solid for signals is concise. Atoms in Dark seem to be more verbose. That's all I can say about them, I haven't used them yet

**Comment by atellmer** [comment]
Naive implementation via atoms

```tsx
import { h, Fragment, component, atom, useComputed, useStore } from '@dark-engine/core';
import { createRoot } from '@dark-engine/platform-browser';

type I18nMessage = {
  'home.hello': string;
};

function fetchMessages(lang: string) {
  return new Promise<I18nMessage>(resolve => {
    setTimeout(() => {
      const map = {
        en: { 'home.hello': 'hello!' },
        it: { 'home.hello': 'Ciao!' },
        es: { 'home.hello': 'Hola!' },
      };

      resolve(map[lang] || map['en']);
    }, 100);
  });
}

const lang$ = atom('en');
const cache$ = atom({
  en: { 'home.hello': 'hello!' }, // fallback
});

function useTranslations() {
  const messages$ = useComputed([lang$, cache$], (lang, cache): I18nMessage => {
    if (cache[lang]) return cache[lang];

    (async () => {
      const messages = await fetchMessages(lang);

      cache$.set(x => ({ ...x, [lang]: messages }));
    })();

    return cache['en'];
  });
  const [messages] = useStore([messages$]);

  return messages;
}

// using

const App = component(() => {
  const messages = useTranslations();

  return (
    <>
      <div>{messages['home.hello']}</div>
      <button onClick={() => lang$.set('en')}>en</button>
      <button onClick={() => lang$.set('it')}>it</button>
      <button onClick={() => lang$.set('es')}>es</button>
    </>
  );
});

createRoot(document.querySelector('#root')).render(<App />);
```

**Comment by atellmer** [comment]
Another variant (more better IMHO)

```tsx
import { h, Fragment, component, atom, useEffect, useUpdate } from '@dark-engine/core';
import { createRoot } from '@dark-engine/platform-browser';

type I18nMessage = {
  'home.hello': string;
};

function fetchMessages(lang: string) {
  return new Promise<I18nMessage>(resolve => {
    setTimeout(() => {
      const map = {
        en: { 'home.hello': 'hello!' },
        it: { 'home.hello': 'Ciao!' },
        es: { 'home.hello': 'Hola!' },
      };

      resolve(map[lang] || map['en']);
    }, 100);
  });
}

const lang$ = atom('en');
const cache = {
  en: { 'home.hello': 'hello!' }, // fallback
};

function useTranslations() {
  const lang = lang$.get();
  const update = useUpdate();

  useEffect(() => {
    return lang$.on(({ next }) => {
      if (!cache[next]) {
        (async () => {
          cache[next] = await fetchMessages(next);
          update();
        })();
      } else {
        update();
      }
    });
  }, []);

  return cache[lang] || cache['en'];
}

const Title = component(() => {
  const messages = useTranslations();

  console.log('title');
  return <h1>{messages['home.hello']}</h1>;
});

const App = component(() => {
  console.log('app');
  return (
    <>
      <Title />
      <button onClick={() => lang$.set('en')}>en</button>
      <button onClick={() => lang$.set('it')}>it</button>
      <button onClick={() => lang$.set('es')}>es</button>
    </>
  );
});

createRoot(document.querySelector('#root')).render(<App />);
```

**Comment by atellmer** [comment]
The ideal variant is combination of Context and Atoms (Context for dependency injection without props drilling, Atoms for small updates, no extra rerenders, no extra fetch for messages)

```tsx
import {
  type DarkElement,
  type WritableAtom,
  h,
  Fragment,
  component,
  useAtom,
  useStore,
  useMemo,
  useEffect,
  useContext,
  createContext,
} from '@dark-engine/core';
import { createRoot } from '@dark-engine/platform-browser';

type Lang = 'en' | 'it' | 'es';

type I18nMessage = {
  'home.hello': string;
};

function fetchMessages(lang: string) {
  return new Promise<I18nMessage>(resolve => {
    setTimeout(() => {
      const map = {
        en: { 'home.hello': 'hello!' },
        it: { 'home.hello': 'Ciao!' },
        es: { 'home.hello': 'Hola!' },
      };

      console.log('fetch');

      resolve(map[lang] || map['en']);
    }, 100);
  });
}

type TranslationsContextValue = {
  lang$: WritableAtom<Lang>;
  messages$: WritableAtom<Partial<Record<Lang, I18nMessage>>>;
  fallback: Lang;
};

const TranslationsContext = createContext<TranslationsContextValue>(null);

type TranslationsProviderProps = {
  slot: (x: TranslationsContextValue) => DarkElement;
};

const TranslationsProvider = component<TranslationsProviderProps>(({ slot }) => {
  const lang$ = useAtom<Lang>('en');
  const messages$ = useAtom({
    en: { 'home.hello': 'hello!' }, // fallback
  });
  const value = useMemo<TranslationsContextValue>(() => ({ lang$, messages$, fallback: 'en' }), []);

  useEffect(() => {
    return lang$.on(({ next }) => {
      if (!messages$.get()[next]) {
        (async () => {
          const messages = await fetchMessages(next);

          value.fallback = next;
          messages$.set(x => ({ ...x, [next]: messages }));
        })();
      } else {
        messages$.set(x => ({ ...x }));
      }
    });
  }, []);

  return <TranslationsContext.Provider value={value}>{slot(value)}</TranslationsContext.Provider>;
});

function useTranslations() {
  const { lang$, messages$, fallback } = useContext(TranslationsContext);
  const [messages] = useStore([messages$]);
  const t = messages[lang$.get()] || messages[fallback];

  return { lang$, t };
}

// using
const Title = component(() => {
  const { t } = useTranslations();

  console.log('title');
  return <h1>{t['home.hello']}</h1>;
});

const App = component(() => {
  console.log('app');
  return (
    <TranslationsProvider>
      {({ lang$ }) => (
        <>
          <Title />
          <Title />
          <button onClick={() => lang$.set('en')}>en</button>
          <button onClick={() => lang$.set('it')}>it</button>
          <button onClick={() => lang$.set('es')}>es</button>
        </>
      )}
    </TranslationsProvider>
  );
});

createRoot(document.querySelector('#root')).render(<App />);
```

**Comment by Coachonko** [comment]
I'm investigating the behavior of context provider in Dark.
`return <TranslationsContext.Provider value={context}>{slot}</TranslationsContext.Provider>`

In what situations and which `slot` components rerender? 
I am observing that all components in `slot` rerender, even those that do not consume context through `useContext`.
I am not sure if this is expected or if I did something stupid (typical of me ngl).

**Comment by atellmer** [comment]
The context updates its entire subtree when value changes as one continuous render. The entire subtree is rendered because it is a normal render via the useState setter.

If in the process there are memo components that stop the rendering, then one large render is split into smaller ones and the context begins to update subscriptions in a targeted manner. This approach follows the React approach.

**Comment by Coachonko** [comment]
> The context updates its entire subtree when value changes as one continuous render. The entire subtree is rendered because it is a normal render via the useState setter.

Ok I understand. I assumed it would only rerender context consumers. Thank you for the information.

**Comment by atellmer** [comment]
The idea is that the context is just an internal communication channel, but does not initiate rerenders, so the context value is placed in a useMemo, which will never change (no deps).

The initiators of changes are atoms that cause only consumers to be re-rendered through the useStore.

It might seem that this behavior could only be achieved through the context if it only updated its subscribers and not the entire subtree. But this actually cannot be achieved by default, because the context is required to render from above. We can't just put a memo somewhere inside that will stop the rendering, because then we will need to control when it should stop and when it shouldn't.
This context behavior could be achieved if the context were updated imperatively, something like contextRef.current.mapSubscribers(). Then we could only update subscribers.

As a result, to achieve the desired behavior you should use context + atoms.
