### ISSUE TITLE
Does a `CloneElement` function exist?

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#52]
```js
const Message = component(({ className, defaultMessage, id, ...values }) => {
  const { translator } = useTranslation()
  const { getMessageById, currentLanguage, onError } = translator

  const message = getMessageById(id, defaultMessage)

  if (detectIsString(message)) {
    try {
      const parts = getTranslationParts(currentLanguage, message, values)
      const result = []
      for (let i = 0, len = parts.length; i < len; i++) {
        const part = parts[i]
        if (detectIsVirtualNode(part)) {
          result.push(cloneVNode(part, { key: i })) // cloneVNode/cloneElement doesn't exist
        } else {
          result.push(<Fragment key={i}>{part}</Fragment>)
        }
      }
      return <>{result}</>
    } catch (error) {
      onError(new TranslationError(id, currentLanguage))
    }
  }

  return <>{String(message)}</>
})

export default Message
```

I am looking to clone an element in an iteration. I see [here](https://github.com/atellmer/dark/tree/master/packages/core#list-rendering) that keys can be added to elements in iterations.

**Comment by Coachonko** [comment]
In react cloneElement is not marked as legacy, it is only recommended to use different approaches if possible.

I would use a `render prop` approach but that requires the users of the internationalization library to provide a prop every time, and that creates friction with the user.

Regarding keys: notes, I'm still prototyping, this will change.

**Comment by atellmer** [comment]
You can always use the default renderItem functions that come with the library. And store them in context, if necessary. And if the user needs custom functions, he can write his own and implement them in the configuration.

Anyway, these are my thoughts, divorced from the context of the task. If you had written why the i18n library needed not raw translation data in the form of text, but nodes, then I would have understood you better. Do you mean some kind of string formatting, such as formatting monetary amounts for different locales?

**Comment by Coachonko** [comment]
> You can always use the default `renderItem` functions that come with the library. And store them in context, if necessary. And if the user needs custom functions, he can write his own and implement them in the configuration.

I am going to look into this. Thank you for the information

> Anyway, these are my thoughts, divorced from the context of the task. If you had written why the i18n library needed not raw translation data in the form of text, but nodes, then I would have understood you better.

My plan was to take nodes in and get them out with strings interpolated. I think it was a bad idea now, I am going to rethink it

**Comment by Coachonko** [comment]
I am playing around with a naive implementation. I have noticed something:
```js
        <Translate
          id='translate.test'
          // defaultMessage='hello <italic>beautiful</italic> <bold>{what}</bold>'
          values={{ what: 'world' }}
          elements={{ italic: <i />, bold: <strong /> }}
        />
        
  const elementsToReplace = Object.keys(elements)

  const result = []
  for (let i = 0, len = elementsToReplace.length; i < len; i++) {
    let iResult = translation
    const dummyElement = elementsToReplace[i]
    const ActualElement = elements[dummyElement]

    // find placeholder
    const opening = `<${dummyElement}>`
    const closing = `</${dummyElement}>`
    const openingLocation = iResult.indexOf(opening)
    if (openingLocation === -1) {
      continue
    }
    const closingLocation = iResult.indexOf(closing)
    if (closingLocation === -1) {
      continue
    }

    // remove placeholder
    iResult = iResult.substring(0, closingLocation) // all before closing tag
    iResult = iResult.substring(openingLocation + opening.length) // all after opening tag

    console.log(<ActualElement>{iResult}</ActualElement>) // this is a TagVirtualNode, I expected a factory
```

As you can see by the comment, I am getting an element there instead of a factory function. Can this be solved or is it best to change the elements API to this?

```
          elements={{
            italic: (chunk) => <i>{chunk}</i>,
            bold: (chunk) => <strong>{chunk}</strong>
          }}
```
This seems to work well, but there would be a ton of `(chunk) => {chunk}` repetitions in codebases (react-intl does this, I don't like it)

**Comment by Coachonko** [comment]
Do you mind showing me how to test Dark components?
In desperation I've done [this](https://github.com/Coachonko/coachonko.com/blob/master/src/components/Translator/Translate_test.jsx), how do you test human interaction and re-render behavior?

**Comment by atellmer** [comment]
I see that you are taking the rendering method from `platform-server`. This is suitable if your task is simply to check that it can work in SSR mode.

In order to test the work in the browser, you need to configure `jsdom` - this is a library for DOM emulation in the Node.js environment. Perhaps such an implementation has already been written for Bun.

And then the process is similar to regular programming: you create an element via `const host = document.createElement('div')` (the document will be available globally in the test environment using jsdom) and send it to `createRoot(host).render(<App />)`. Then you check `host.innerHTML`. (also after rendering, you may need to wait for `setTimeout` for the effects that are in your application to be executed).

To simulate user events, you need to generate them via `new Event()`. An example implementation is [here](https://github.com/atellmer/dark/blob/master/test/utils.ts#L42) (click event).

**Comment by Coachonko** [comment]
Thank you
