### ISSUE TITLE
Server-side styled Dark components documentation

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#56]
I have tried to setup SSR with renderToString and styled dark components and I found it confusing.
The documentation says [`a provider can be added to your component tree, which accepts styles through a context API`](https://github.com/atellmer/dark/tree/master/packages/styled#server-side-rendering) but it is not shown how to do that, instead `String.replace` method is used.
The `String.replace` method seems to work, but it is not clear if the provider is implemented or not yet

**Comment by atellmer** [comment]
In the code `Provider` is added automatically via `sheet.collectStyles()` [link](https://github.com/atellmer/dark/blob/master/packages/styled/src/server/sheet.ts#L18)

```tsx
const app = await renderToString(sheet.collectStyles(<App />));
const tags = sheet.getStyleTags();
```
