### ISSUE TITLE
Utility function to detect whether a path matches a web-router route

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#59]
I need a function that would return me if a route is matched for a given path.
Something like `matchRoute(routesArray, path)` which return null or an array of matched routes.
This is because I need to be able to "filter" valid requests before hanging them to my Dark server script, otherwise Dark will render the application and return HTML when a non-existing file is requested.
With a `matchRoute` function that returns `null` or an array where `matchRouteArr[0].path === '**'`, I can immediately send an error 404, making my Dark server more efficient

```js
import { join } from 'bun:path'

// tryFiles returns a static file from the build directory, if found. otherwise it passes the request
// to the specified handler.
export function tryFiles (elysiaContext, publicDir, handler) {
  const absolutePath = join(process.cwd(), publicDir, elysiaContext.path)

  // prevent relative path abuse
  const allowedBasePath = join(process.cwd(), publicDir, '/')
  if (!absolutePath.startsWith(allowedBasePath)) {
    return elysiaContext.error(403) // 'Forbidden'
  }

  if (absolutePath === allowedBasePath) {
    return handler(elysiaContext)
  }

  const file = Bun.file(absolutePath)
  // TODO if file is missing and not an application route, the handler (Dark) will return HTML. This is a problem.
  // Check application routes: if match give request to Dark, otherwise return elysiaContext.error(404) immediately
  if (file.size === 0) {
    return handler(elysiaContext)
  }

  return file
}
```

Update: I think there is a huge flaw in what I was attempting to do, and I will change my logic for sure. However, this function may still be useful to have.

**Comment by atellmer** [comment]
It seems that this will be double work: checking whether such a route exists before rendering and then again checking whether such a route exists inside the application during the rendering process. I'm not sure that this problem needs to solve at the library level, and not at the application architecture level.

**Comment by Coachonko** [comment]
Yep I solved that problem differently.
I do not have a need for that kind of function any more.
for some reason, such a function seems useful to me, but I can't think of any uses for it either.

**Comment by Coachonko** [comment]
Actually, I think I have a valid use for such a function now.
As you may have seen from from the starter project I linked in previous issues, I am adding a property "seo" to route objects.
With this property I can match a route with its SEO data, which is kept in an object with its translations.
The assumption is that, at every server request, the path can be used to match the correct route and find the correct SEO data. This data is then used to build the response.

I had written a simple function that could match the path to the route correctly before, but it doesn't work with nested routes. Writing my own implementation of such a function would be less reliable than having Dark's web-router expose the same algorithm with a function that can be used in this situation.

**Comment by atellmer** [comment]
Maybe for SEO we need something like this? [link](https://react.dev/reference/react-dom/components/meta)
Only we need to do it through the context like styled components do.

**Comment by Coachonko** [comment]
> Maybe for SEO we need something like this? [link](https://react.dev/reference/react-dom/components/meta) Only we need to do it through the context like styled components do.

I am not sure about this. I have never used current canary react.
Today I will try a different approach and will come back with more thoughts.

**Comment by Coachonko** [comment]
I am still testing but I suspect `const lastPathnameSegment = pathname.substring(pathname.lastIndexOf('/') + 1)` works good enough. It is not a perfect solution, but no framework out there seems to have a perfect solution to this problem
