### ISSUE TITLE
css fragment in GlobalStyle

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#71]
Do you know why using css fragments in GlobalStyle does not seem to work (neither server nor browser)?

```js
const typography = () => css` 
  body {
    text-rendering: optimizeLegibility;
    color: ${props => props.theme.black};
    line-height: 1.5;
  }
`

const GlobalStyle = createGlobalStyle`
  body {
    margin: 0;
    min-height: 100%;
    background-color: ${props => props.theme.white};
    overflow-y: hidden;
  }

  #dark-root {
    isolation: isolate;
  }

  /* ${typography} breaks everything */
  ${() => typography} /* does not break everything but doesn't render anything either */
  /* ${() => typography()} breaks everything */
`

const lightColors = {
  white: '#f6f2ef',
  black: '#1e1f1f',
}

const light = {
  ...lightColors,
  borderStyle: `solid 1px ${lightColors.black}`
}

const Theme = component(({ slot }) => {
  const [theme, setTheme] = useState(light)
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyle />
      {slot}
    </ThemeProvider>
  )
})

const Root = component(({ slot }) => {
  return <Theme><GlobalStyle />{slot}</Theme>
}
```

Update: I have since noticed that `${() => typography()}` does render the styles, but everything breaks nonetheless, I will investigate more (error: RangeError: Maximum call stack size exceeded.)

**Comment by Coachonko** [comment]
```
const GlobalStyle = createGlobalStyle`
  /* ${() => typography()} error: RangeError: Maximum call stack size exceeded */
  body {
    margin: 0;
    min-height: 100%;
    background-color: ${props => props.theme.white};
    overflow-y: hidden;
  }

  #dark-root {
    isolation: isolate;
  }

  ${() => typography()} /* works here */
`
```

**Comment by atellmer** [comment]
Correct way:

```tsx
const typography = props => css`
  body {
    text-rendering: optimizeLegibility;
    color: ${props.theme.black};
  }
`;
```

more correct way (without body selector, because is not resusable)
```tsx
const typography = props => css`
   text-rendering: optimizeLegibility;
   color: ${props.theme.black};
`;

const GlobalStyle = createGlobalStyle`
  body {
    ${typography};
  }
`;
```

You can use 

```tsx
const typography = css`` // without function
```

but then the generated style will be mixed into own component styles.

if you are using 

```tsx
const typography = () => css``
```

This style will be recognized as dynamic style and it generates uniq class for reusing in another components who may use `typography`.

**Comment by atellmer** [comment]
> When I do this, the app breaks because props is undefined

Yes. If you need props in your css fragment, you should use `() => css` syntax. Similar approach is also used in `keyframes`.

> what I have seen (from googling) styled-components doesn't have this problem

Maybe. They are using own different code base.

**Comment by atellmer** [comment]
Working example

```tsx
const typography = props => css`
  body {
    color: ${props.theme.black};
  }
`;

const GlobalStyle = createGlobalStyle`
  body {
    background-color: ${props => props.theme.white};
  }

  ${typography};
`;

const light = {
  white: 'white',
  black: 'black',
};

const black = {
  white: 'black',
  black: 'white',
};

const Theme = component<{ slot: DarkElement }>(({ slot }) => {
  const [theme, setTheme] = useState(light);

  return (
    <ThemeProvider theme={theme}>
      <GlobalStyle />
      {slot}
      <button onClick={() => setTheme(x => (x === light ? black : light))}>toggle</button>
    </ThemeProvider>
  );
});

const Root = component<{ slot: DarkElement }>(({ slot }) => {
  return <Theme>{slot}</Theme>;
});

const App = component(() => {
  return (
    <Root>
      <h1>Title</h1>
    </Root>
  );
});

createRoot(document.querySelector('#root')).render(<App />);
```

**Comment by Coachonko** [comment]
> Working example

I see, yes this works for me as well.
Previously I made a mistake when using `const typography = props => css`, I did not change `color: ${props => props.theme.black};` to `color: ${props.theme.black};`

> They use their own code base.

Of course, I was just thinking that it would be nice if styled did that too. Though I do not think it is a big deal, with some more examples, even here in the issues, the way dark's styled works will be better documented and all differences will be clearer

**Comment by atellmer** [comment]
It will throw an error in this case in the new version

**Comment by Coachonko** [comment]
The new error is very useful, it helped me fix one useless nested function call. :+1: 
However, the error doesn't actually say which file has the bad syntax. Prettier errors would be nicer

**Comment by atellmer** [comment]
Perhaps the error should include the piece of CSS itself.
