### ISSUE TITLE
Question about data useQuery variables

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#85]
I have a component with this sort of query
```js
// suppose the parent component has a button that toggles an `availability: 'true'` property in the `params` object
const ShopItems = component(({ params }) => {
  console.log(params) // diagnose params changes
  const api = useApi()
  const { data, isFetching, error } = useQuery(
  'tools',
  (params) => api.catalogRetrieve({ category: 'tools', ...params }),
  { variables: params, extractId: () => hashKey(params) },
)

```
According to the documentation [here](https://github.com/atellmer/dark/tree/master/packages/data#usequery), this setup allows the query to refetch whenever variables change.

With this code, a refetch happens when the `params` object changes from 
Case A: returns an array of 10 items
```json
{
    "status": "public"
}
```
to 
Case B: returns an array of 4 items
```json
{
    "status": "public",
    "availability": "true"
}
```
Then, if the property `availability` is removed from the `params` object again, a refetch does not happen and `data` does not change. `data` returned is still an array of 4 items instead of 10. No errors are thrown either.
I am confused because I expected it to maybe not refetch, because the key already exists in cache, but I did not expect the data object to not change either.
What am I doing wrong?

**Comment by Coachonko** [comment]
I can see [here](https://github.com/atellmer/dark/blob/master/packages/data/src/use-query/use-query.ts#L195) that `record?.valid` evaluates to `true` when the example object above goes from B to A, therefore a refetch won't happen.
This is what I expected.
However the hook does not return any [data](https://github.com/atellmer/dark/blob/master/packages/data/src/use-query/use-query.ts#L116) when going fro B to A.

**Comment by atellmer** [comment]
As far as I understand, it looks like you get old data from the cache. In fact, `extractId` - says that he needs an ID, that is, this is a case when you have entities with unique IDs, such as products or users. In your case, your id (`{"status": "public"}`) is not quite what you need. Simply put, this is not your case.
In order to re-get data, you must use the `refetch` method that returns `useQuery` inside the `useEffect`.

**Comment by Coachonko** [comment]
I do want to get the old data from cache when going back to A from B, without refetching.

What I am observing is that I am getting the data associated with the wrong cacheId.

I use a `hashKey` function similar to [$extractId](https://github.com/atellmer/dark/blob/master/packages/data/src/use-query/use-query.ts#L285), this function sorts the keys of the object used as id, similar to [this one](https://github.com/TanStack/query/blob/main/packages/query-core/src/utils.ts#L205).
The objective is to create a reliable unique key for A and B. 

I expected to obtain a behavior similar to [this](https://www.apollographql.com/docs/react/data/queries/#caching-query-results). From the `console.log(state)` I've done, it seems like the `cacheId` is being updated correctly in the state, but the `data` seems to not change and remain on the latest fetched data instead of the one associated with the `cacheId`. Am I understnding this correctly?

I can try to use a refetch strategy with useEffect as you suggested to get things working for now.

**Comment by atellmer** [comment]
I will try to recreate a similar example to understand why the data remain old.

**Comment by Coachonko** [comment]
I have done [this repro](https://stackblitz.com/edit/darkapp-ccz57rk-1zhv6b?file=index.tsx) relatively quickly.

**Comment by atellmer** [comment]
It's a bug.
Working code in `useQuery`

```tsx
  useEffect(() => {
    const shouldSkip = isHydration || lazy || pending || state.isFetching || record?.valid;

    // needs a test
    // https://github.com/atellmer/dark/issues/85
    if (shouldSkip) {
      if (record?.valid) {
        state.data = record.data; // this
        update();
      }
    } else {
      refetch();
    }
  }, [...mapRecord(variables)]);
```

**Comment by Coachonko** [comment]
I can confirm that the change seems to fix the issue in my application. Although I admit I don't know how to write browser tests.
If you can push an update for this it would be greatly appreciated :heart:

**Comment by atellmer** [comment]
I hope to release the update this week.

**Comment by atellmer** [comment]
1.4.2 is available
