### ISSUE TITLE
Debugging $$scope().getCursorFiber errors

### ISSUE THREAD

**Issue by Coachonko** [atellmer/dark#94]
Hi, since the last update I am getting these errors and nothing renders, not even `<!-- dark-matter -->`.
This seemed to happen with the `slot` of my [`TranslationsProvider` component](https://github.com/Coachonko/wareme/blob/master/packages/translations/src/TranslationsProvider.jsx).
I have attempted to replicate the issue [here](https://github.com/Coachonko/wareme/tree/master/examples/translations) with no success.

```
18222 | };
18223 | var Memo2 = memo6(component12(({ getValue }) => getValue()), (p4, n3) => detectAreDepsDifferent2(p4.deps, n3.deps));
18224 | 
18225 | // ../../node_modules/@dark-engine/core/dist/esm/internal/internal.js
18226 |   return $$scope2().getCursorFiber();
                           ^
error: TypeError: undefined is not an object (evaluating '$$scope2().getCursorFiber')
      at onError (/home/coachonko/website/packages/storefront/build/server/index.js:14701:26)
      at /home/coachonko/website/packages/storefront/build/server/index.js:14641:14
      at forEach (:1:11)
      at emit (/home/coachonko/website/packages/storefront/build/server/index.js:211:63)
      at workLoop (/home/coachonko/website/packages/storefront/build/server/index.js:1755:22)
      at performWorkUntilDeadline (/home/coachonko/website/packages/storefront/build/server/index.js:1368:47)
      at forEach (:1:11)
      at emit (/home/coachonko/website/packages/storefront/build/server/index.js:211:63)
      at /home/coachonko/website/packages/storefront/build/server/index.js:1243:24
```

The trace doesn't give me any useful information, all of these lines point to internal functions. For example, the deepest point, 1243:24 point to this
```js
class MessagePort {
  channel;
  offs = [];
  constructor(channel) {
    this.channel = channel;
  }
  on(event, callback) {
    const off = this.channel.on(event, callback);
    this.offs.push(off);
  }
  postMessage(value15) {
    platform.spawn(() => {
      this.channel.emit("message", value15);
    });
  }
  unref() {
    this.offs.forEach((x3) => x3());
  }
}
```

How would you find the source of such issue? I am lost

14:36: ~~after further testing I am suspecting the [useInView](https://github.com/Coachonko/wareme/tree/master/packages/use-in-view) hook, I have also seen `error: Error: [@dark-engine/core]: The function was not installed by renderer!`~~ I was wrong
14:52: It was caused by [useScrollbarWidth](https://github.com/Coachonko/wareme/tree/master/packages/use-scrollbar-width), now investigating why

**Comment by atellmer** [comment]
It looks like your build is broken or something, because the changes in 1.4.2 are minimal and all 542 tests are green.

$$scope() should return an instance of the global app store. If it is undefined, then we are trying to access it outside the renderer.

If your error is in platform-server, then you can put a breakpoint in https://github.com/atellmer/dark/blob/5dcdc4124565f0ebbd87f7cf7ff24a157dfb01ce/packages/platform-server/src/render/render.ts#L59

and see what $scope, rootId are equal to, the scope itself is created in setRootId on the line above.

But again, it seems like something is wrong with your build or some Bun cache.

**Comment by Coachonko** [comment]
Likely bun cache, it's now magically working fine. 
I cleared the cache before too, several times, but now it's good.
I spent 5 hours on this, changed 0 characters, and now it just works.
We are developers :grimacing: 

Thank you for the tips, I am sure they will come in handy next time
